### ISSUE TITLE
Remove '#'

### ISSUE THREAD

**Issue by thansen0** [WisconsinEngineerMagazine/Wisconsin-Engineer#14]
Look into removing the '#' from the URL.

**Comment by earlejam** [comment]
And change the promo page's url from promo to something more descriptive

**Comment by earlejam** [comment]
https://help.dreamhost.com/hc/en-us/articles/215747748-How-can-I-redirect-and-rewrite-my-URLs-with-an-htaccess-file-

**Comment by earlejam** [comment]
After adding an .htaccess file to the server that handles redirecting the route after a page refresh, the hashtags are officially gone from our urls.
