### ISSUE TITLE
Add https to site

### ISSUE THREAD

**Issue by thansen0** [WisconsinEngineerMagazine/Wisconsin-Engineer#16]
Currently the main site isn't secured, and at some point we'd like to secure it with https.  I believe google now offers a free solution.

**Comment by earlejam** [comment]
Certificate is installed, next step is getting .htaccess file to actually do its job:
https://help.dreamhost.com/hc/en-us/articles/215747758-How-do-I-force-my-site-to-load-securely-with-an-htaccess-file-

**Comment by earlejam** [comment]
All traffic should now redirect to the secure version of the site.
