### ISSUE TITLE
Fix 'Join Us' Link

### ISSUE THREAD

**Issue by earlejam** [WisconsinEngineerMagazine/Wisconsin-Engineer#18]
The 'Join Us' link on the footer of the page currently leads to a 404. It's as simple as figuring out what it used to lead to and re-linking it.

**Comment by juniorq1995** [comment]
What about the other page links?

**Comment by earlejam** [comment]
Good catch--it looks like the version of the site I reverted to actually had problems, but wasn't uploaded via FTP so the problems never saw the light of day. I'll go back and fix it.
