### ISSUE TITLE
Fix Photo Contest, Advertise Links

### ISSUE THREAD

**Issue by earlejam** [WisconsinEngineerMagazine/Wisconsin-Engineer#19]
Something is slightly off in the code that is preventing Angular from realizing we're selecting that tab. Not a big deal since the photo contest is done, but should work regardless.

**Comment by juniorq1995** [comment]
Thank you for fixing it!

**Comment by earlejam** [comment]
Finally got it fixed for real. I had to clear my cache to realize it, so if it still seems broken, give that a try.

**Comment by juniorq1995** [comment]
Hey, you know how styling changes in the various css files are also present
in a bug mush in main.css. What I've found is that its the main.css updates
that get posted to the website and I'm curious if there's a way to have it
be updated automatically from the changes we make in the other files it
gets fed from.

**Comment by earlejam** [comment]
@juniorq1995 Yeah--I bet there's a way to make that happen, though I don't have experience doing something like that. Go ahead and make a new issue if you'd want to look into it!

**Comment by juniorq1995** [comment]
Its called Gulp, and the Ionic Framework we use must have some sort of file
we can run that compiles all the less and css files into the main.css file
