### ISSUE TITLE
Add office hours, deadlines/distribution dates to embedded google calendar

### ISSUE THREAD

**Issue by mitchas** [WisconsinEngineerMagazine/Wisconsin-Engineer#3]

**Comment by thansen0** [comment]
The calendar will hold things like reoccurring office hours/weekly meetings & deadlines/release dates.  The calendar can be made however you best see fit; either with something like google calendars or office 365 calendars or another service/library, just try to make it editable by people outside the web team (so avoid .json if possible).

**Comment by juniorq1995** [comment]
I messed around with a couple of different formats and settled on a simple google calendar embed. This way I can share the calendar with all the leaders and they can add to calendar with personal email addresses. Long term we should move the master calendar to the WEM google account.
