### ISSUE TITLE
Create a system to upload staff lists from Spreadsheet to website

### ISSUE THREAD

**Issue by earlejam** [WisconsinEngineerMagazine/Wisconsin-Engineer#42]
Not sure exactly what this could look like, but here's a few ideas:

- Google sheets spreadsheet holds staff lists for every department. Write some google apps script to write the staff into the corresponding html/JS staff file. Write some code (CRON job?) on the web host to pull this file every day at 3am, updating the web page.

OR

- Google sheets spreadsheet holds staff lists for every department. Write the google apps script to write staff in the same way as above. Automatically push the staff changes on days that it detects changes to the file. On the web host, install Git and clone our repo. Either have it automatically pull every night at 3am or just fetch, only pulling if changes have been detected. Would have to make sure it would only pull the one file, otherwise merge conflicts could break the site temporarily.

**Comment by cjkenney** [comment]
Google just released a new Docs API, could be useful as a CMS:
https://developers.google.com/sheets/api/

**Comment by earlejam** [comment]
Interesting, that could eliminate the need to write custom google apps scripts. Nice tip pal 👍

**Comment by thenerdjake** [comment]
Gonna close but if you want reopened just reopen it
