### ISSUE TITLE
Update Staff

### ISSUE THREAD

**Issue by thansen0** [WisconsinEngineerMagazine/Wisconsin-Engineer#7]
Currently we have the heads updated but need to update the staff on the main site.  Pester web heads for list, we should be getting it soon.

**Comment by rkreiter22** [comment]
[Updated Staff List](https://docs.google.com/document/d/1SfoQHbiS6CNSBo6iHUOm5ystz6oXeYJRhZrJUme7TFY/edit?usp=sharing)
